In [1]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import math

img = Image.open('images/muralla-china2.jpg')
np_img = np.array(img)

plt.imshow(img)
plt.show()

<Figure size 640x480 with 1 Axes>

In [3]:
def pooling(image,factor):
    
    x = factor
    
    while():
        for i in range(factor):
            for j in range(factor):
                p += factor

In [4]:
def averageMethod(RGB_image):
  
    r, g, b = RGB_image[:,:,0], RGB_image[:,:,1], RGB_image[:,:,2]
    arr = 0.2989 * r + 0.5870 * g + 0.1140 * b

    return arr

In [5]:
np_img_bw = averageMethod(np_img)
print(np_img_bw)

[[236.882  236.882  236.882  ... 225.1713 223.1715 223.1715]
 [236.882  236.882  236.882  ... 225.1713 224.1714 224.1714]
 [236.882  236.882  236.882  ... 225.1713 224.1714 224.1714]
 ...
 [113.2463 112.2464 112.2464 ... 142.7361 139.7364 139.7364]
 [113.2463 111.2465 108.2468 ... 139.7364 139.7364 139.7364]
 [110.1496 111.1495 111.1495 ... 141.7362 139.7364 139.7364]]


## Convolutions and pooling
---
**Convolutions**

In math, a convolution is a mathematical operator that transforms two given functions *f* and *g* in a third function that in a certain way represents the magnitude between *f* and a moved and inverted version of *g*.

One of the challenges on computer vision is that the imputs can be really big. These operations help to make smaller the image and less complex the processing to the next layers of the neural network.

I.e: Edges detection of an image can be helped by some convolutional filters which find vertical and horizontal edges

We can start simulating the image by an array, then process it in the **convolutional** function with a given filter and return the result. The filter is given as well.

youtube explanation: https://www.youtube.com/watch?v=XuD4C8vJzEQ&list=PLkDaE6sCZn6Gl29AoE31iwdVwSG-KnDzF&index=2

In [6]:
def convolution(image, _filter):
    
    columns,rows = image.shape[0], image.shape[1]
    
    result = np.zeros((columns-2, rows-2))
    
    for x in range(1,columns-1):
        for y in range(1,rows-1):
            for j in range(_filter.shape[0]):
                for i in range(_filter.shape[1]):
#                     print(image[x - 1 + i][y  - 1 + j], "*",_filter[i][j],"=",image[x - 1 + i][y  - 1 + j] * _filter[i][j])
                    result[x-1][y-1] += image[x - 1 + i][y  - 1 + j] * _filter[i][j]
#             print()
        
    return result

In [7]:
# arr = np.array([[3,0,1,2,7,4],
#                 [1,5,8,9,3,1],
#                 [2,7,2,5,1,3],
#                 [0,1,3,1,7,8],
#                 [4,2,1,6,2,8],
#                 [2,4,5,2,3,9]])

f_verticalLines = np.array([[1,0,-1],
                           [1,0,-1],
                            [1,0,-1]])

f_horizontalLines =  np.array([[-1,-2,-1],
                               [0,0,0],
                                [1,2,1]])

In [8]:
new_img_bw = convolution(np_img_bw,f_horizontalLines)
new_img_bw

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  9.99900000e-01,  2.99970000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -2.99970000e+00, -2.84217094e-14,  2.99970000e+00],
       [-3.99960000e+00, -3.99960000e+00, -3.99960000e+00, ...,
        -3.99960000e+00, -2.99970000e+00, -9.99900000e-01],
       ...,
       [ 2.98212000e+01,  3.85923000e+01,  5.31348000e+01, ...,
        -3.99960000e+00,  1.99980000e+00, -9.99900000e-01],
       [ 7.91130000e+00, -8.79000000e-02,  1.91190000e+00, ...,
        -2.59974000e+01, -1.29987000e+01, -2.99970000e+00],
       [-6.38740000e+00, -6.15940000e+00, -1.07029000e+01, ...,
        -4.99950000e+00, -1.99980000e+00, -9.99900000e-01]])

In [9]:
im_img_bw = Image.fromarray(np_img_bw)
im_img_bw.show()

In [10]:
im_img_bw_compact = Image.fromarray(convolution(np_img_bw,f_horizontalLines))
im_img_bw_compact.show()