### SciKit Preprocessing

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
import numpy as np

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[67, 12],
       [69, 45],
       [ 5, 54],
       [94, 62],
       [36, 13],
       [60, 47],
       [66, 27],
       [69, 49],
       [87, 52],
       [36, 33]])

In [6]:
scaler_model = MinMaxScaler()

In [7]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
scaler_model.fit(data)

/home/miguel/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data)

array([[0.69662921, 0.        ],
       [0.71910112, 0.66      ],
       [0.        , 0.84      ],
       [1.        , 1.        ],
       [0.34831461, 0.02      ],
       [0.61797753, 0.7       ],
       [0.68539326, 0.3       ],
       [0.71910112, 0.74      ],
       [0.92134831, 0.8       ],
       [0.34831461, 0.42      ]])

In [10]:
scaler_model.fit_transform(data)

/home/miguel/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.69662921, 0.        ],
       [0.71910112, 0.66      ],
       [0.        , 0.84      ],
       [1.        , 1.        ],
       [0.34831461, 0.02      ],
       [0.61797753, 0.7       ],
       [0.68539326, 0.3       ],
       [0.71910112, 0.74      ],
       [0.92134831, 0.8       ],
       [0.34831461, 0.42      ]])

In [11]:
import pandas as pd

In [16]:
mydata=np.random.randint(0,101,(50,4))

In [18]:
df = pd.DataFrame(data=mydata,columns = ['f1','f2','f3','label'])

In [20]:
df

f1  f2   f3  label
0    17  22   28     47
1    80  46   50      9
2    11  29   95     65
3    97  20   70     83
4    45  49   99     86
5    26  85   20     53
6    32  68  100      0
7    33   4   10     50
8     7  99   94     27
9    57  62   69     74
10   45  12   62     38
11   60  17   13     70
12   72  53   80     55
13   72  71   45     30
14   88  80   67     51
15   35   2   67     82
16   19  89   87     96
17   58  18   52     46
18   62  78    0     59
19   11  98   68     60
20   92  11   66     22
21   77  60   35     53
22    7  72    2      9
23   67  17   86     12
24  100  55   79     50
25   28  39    4      7
26   12  23    3     34
27   20  69   26     52
28    3  89   66      9
29   68  46   47     82
30   48  92   45     48
31   14  79   70     25
32  100  94   83      8
33   38  55   39     19
34   30  82   39     99
35   42  32   87     75
36   63  72   69     73
37   43  68    7     24
38   30  55    2     95
39   84  15   52      2
40   77  18   57     19
41   47  41   44      4
42   74  47   50     89
43   14  11   22     88
44   81  67    9     26
45   18  38   88      0
46    8  95   37     60
47   32  88   47     79
48   21  73   83     92
49   57  38   76     46

In [26]:
X = df[['f1','f2','f3']]

In [27]:
y = df['label']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_train = train_test_split(X, y, test_size=0.33,random_state=42)

In [30]:
X_train.shape

(33, 3)

In [31]:
X_test.shape

(17, 3)